# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20180918_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='markup',
            field=models.CharField(blank=True, choices=[('crl', 'Creole'), ('rst', 'reStructuredText'), ('txl', 'Textile'), ('mrk', 'Markdown')], max_length=3, null=True, verbose_name='Content Markup'),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='old_markup',
            field=models.CharField(blank=True, choices=[('crl', 'Creole'), ('rst', 'reStructuredText'), ('txl', 'Textile'), ('mrk', 'Markdown')], max_length=3, null=True, verbose_name='Article Content Markup'),
        ),
    ]
