# Generated by Django 2.2.28 on 2023-01-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0004_auto_20221208_1815"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="deleted",
            field=models.BooleanField(
                default=False, help_text="Check to mark as deleted"
            ),
        ),
    ]
