# Generated by Django 5.2.10 on 2026-01-31 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0006_alter_changeset_editor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="markup",
        ),
        migrations.RemoveField(
            model_name="changeset",
            name="old_markup",
        ),
    ]
