# Generated by Django 2.2.28 on 2023-04-16 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):
    replaces = [
        ("news", "0001_initial"),
        ("news", "0002_auto_20170417_1857"),
        ("news", "0003_auto_20221208_1758"),
        ("news", "0004_remove_post_tags"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("image", models.ImageField(upload_to=news.models.get_upload_name)),
            ],
            options={
                "ordering": ("title",),
                "db_table": "news_categories",
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(unique_for_date="publish", verbose_name="slug"),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Text entered here will be rendered using Markdown",
                        verbose_name="body",
                    ),
                ),
                ("tease", models.TextField(blank=True, verbose_name="tease")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Draft"), (2, "Public")],
                        default=2,
                        verbose_name="status",
                    ),
                ),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                ("publish", models.DateTimeField(verbose_name="publish")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("categories", models.ManyToManyField(blank=True, to="news.Category")),
            ],
            options={
                "ordering": ("-publish",),
                "db_table": "news_posts",
                "verbose_name": "post",
                "verbose_name_plural": "posts",
                "get_latest_by": "publish",
            },
        ),
    ]
