# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20190409_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesetting',
            name='medium',
            field=models.CharField(choices=[('1', 'Email')], max_length=1, verbose_name='medium'),
        ),
    ]
