# Generated by Django 4.2.27 on 2025-12-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_auto_20190409_0924"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticetype",
            name="default",
        ),
        migrations.AddField(
            model_name="noticetype",
            name="send_default",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="noticesetting",
            name="medium",
            field=models.CharField(
                choices=[("1", "Email")],
                default="1",
                max_length=1,
                verbose_name="medium",
            ),
        ),
        migrations.AlterField(
            model_name="noticetype",
            name="label",
            field=models.CharField(max_length=40, unique=True, verbose_name="label"),
        ),
    ]
