# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlscheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilities',
            name='avail_time',
            field=models.DateTimeField(default=0, help_text='this user is available for this whole hour'),
        ),
    ]
