# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-03 12:38


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threadedcomments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freethreadedcomment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='freethreadedcomment',
            name='parent',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.RemoveField(
            model_name='threadedcomment',
            name='ip_address',
        ),
        migrations.DeleteModel(
            name='FreeThreadedComment',
        ),
    ]
