# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-31 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadedcomments', '0002_auto_20181003_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadedcomment',
            name='markup',
            field=models.IntegerField(blank=True, choices=[(1, 'markdown'), (2, 'textile'), (3, 'restructuredtext'), (5, 'plaintext')], default='markdown', null=True),
        ),
    ]
