# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-18 09:01


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wlimages", "0002_remove_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="editor_ip",
        ),
    ]
