# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wlscreens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('screenshot', models.ImageField(storage=wlscreens.models.OverwriteStorage(), upload_to=wlscreens.models.screenshot_path)),
                ('thumbnail', models.ImageField(editable=False, storage=wlscreens.models.OverwriteStorage(), upload_to=wlscreens.models.thumbnail_path)),
                ('comment', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='wlscreens.Category')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='screenshot',
            unique_together=set([('name', 'category')]),
        ),
    ]
