# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlscreens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screenshot',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='screenshot',
            name='position',
            field=models.IntegerField(blank=True, default=0, help_text=b'The position inside the category', null=True),
        ),
    ]
