# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-31 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlscreens', '0002_auto_20190410_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='position',
            field=models.IntegerField(blank=True, default=0, help_text='The position inside the category', null=True),
        ),
    ]
