# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-02 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0002_auto_20161001_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_ip',
        ),
    ]
