# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-07 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0003_remove_post_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='official',
            field=models.BooleanField(default=True, help_text='If unset this category is only visible for group Forum Admin or superusers', verbose_name='Official Category'),
        ),
    ]
