# Generated by Django 4.2.25 on 2025-11-01 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pybb", "0006_auto_20221208_1825"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Thumbs Up"),
                            (17, "Thumbs Down"),
                            (34, "Happy"),
                            (51, "Sad"),
                            (68, "Confused"),
                            (85, "Thinking"),
                            (102, "Heart"),
                            (119, "Cheer"),
                            (136, "Rocket"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="pybb.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["image"],
                "unique_together": {("user", "post")},
            },
        ),
    ]
