# Generated by Django 5.2.17 on 2026-10-03 00:57

from django.conf import settings
from django.db import migrations, models


def remove_duplicate_votes(apps, schema_editor):
    """Keep only the first vote of a user per poll.

    Each removed vote also incremented its choice's counter, so take it back.
    """
    Vote = apps.get_model("wlpoll", "Vote")
    Choice = apps.get_model("wlpoll", "Choice")
    duplicates = (
        Vote.objects.values("user", "poll")
        .annotate(count=models.Count("id"), first=models.Min("id"))
        .filter(count__gt=1)
    )
    for duplicate in duplicates:
        extra_votes = Vote.objects.filter(
            user=duplicate["user"], poll=duplicate["poll"]
        ).exclude(id=duplicate["first"])
        for vote in extra_votes:
            Choice.objects.filter(pk=vote.choice_id, votes__gt=0).update(
                votes=models.F("votes") - 1
            )
        extra_votes.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("wlpoll", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_votes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("user", "poll"), name="wlpoll_vote_unique_user_poll"
            ),
        ),
    ]
