# Generated by Django 4.2.17 on 2025-02-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check_input", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspiciousKeyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        help_text="Type lowercase only, spaces allowed",
                        max_length=50,
                        unique=True,
                        verbose_name="Spam Keyword",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Keyword Description"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Spam Keywords",
            },
        ),
    ]
