# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-31 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspiciousinput',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='related model'),
        ),
        migrations.AlterField(
            model_name='suspiciousinput',
            name='text',
            field=models.CharField(max_length=200, verbose_name='suspicious user input'),
        ),
        migrations.AlterField(
            model_name='suspiciousinput',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='related user'),
        ),
    ]
