# Generated by Django 5.2.17 on 2026-10-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check_input", "0002_suspiciouskeyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suspiciousinput",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
