# Generated by Django 4.2.20 on 2025-04-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wlprofile", "0004_auto_20221215_0935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="time_display",
            field=models.CharField(
                default="%ND(Y-m-d,) H:i e", max_length=80, verbose_name="Time display"
            ),
        ),
    ]
