# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-31 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlmaps', '0003_auto_20190712_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='wl_version_after',
        ),
        migrations.AddField(
            model_name='map',
            name='min_wl_version',
            field=models.TextField(blank=True, null=True, verbose_name='Minimum WL version'),
        ),
    ]
