# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-21 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonNoticeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(help_text='E.g.: Translation issues', max_length=50)),
                ('description', models.CharField(help_text='E.g.: Notify me on translation issues', max_length=100)),
                ('send_default', models.BooleanField(default=True, help_text='Default setting for this notice type')),
                ('author_related_default', models.BooleanField(default=True, help_text='Turn off for notice types which are not directly related                   to an add-on author, e.g. mentions in add-on comments.')),
                ('slug', models.SlugField(help_text='Do not change this once it is set', unique=True)),
            ],
            options={
                'verbose_name': 'Addon notice type',
                'verbose_name_plural': 'Addon notice types',
            },
        ),
        migrations.CreateModel(
            name='AddonNoticeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shouldsend', models.BooleanField(default=True)),
                ('author_related', models.BooleanField(default=True)),
                ('notice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wladdons_settings.AddonNoticeType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Addon noticetype/user relationship',
                'verbose_name_plural': 'Addon noticetype/user relationships',
            },
        ),
    ]
